# Configuración del servidor
server.port=8080

# Configuración de la Base de Datos H2 (Embebida)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola web de H2 para ver los datos de los alumnos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar las consultas SQL en la consola por si necesitamos depurar
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
